name: beta_project
description: Home management system using IoT

documentation: https://github.com/Mawueugiio/homesys/blob/dev/README.md

repository: https://github.com/Mawueugiio/homesys/tree/dev

authors:
  - Eugenia

publish_to: "github.com"

version: 0.0.1+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  # Draw SVG (and some Android VectorDrawable (XML)) files on a Flutter Widget.
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^0.17.4

  # Firebase
  #
  firebase_analytics: ^5.0.11
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  firebase_messaging: ^6.0.15

  # The google_fonts package for Flutter
  # https://pub.dev/packages/google_fonts
  google_fonts: ^1.1.0

  # This is a simple Service Locator for Dart and Flutter projects
  # https://pub.dev/packages/get_it
  get_it: ^4.0.2

  # Wraps NSUserDefaults (on iOS) and SharedPreferences (on Android), providing a persistent store for simple data
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.7+2

  # A cross platform plugin for displaying local notifications
  # https://pub.dev/packages/flutter_local_notifications
  flutter_local_notifications: ^1.4.3

  # Route manager
  # https://pub.dev/packages/auto_route
  auto_route: ^0.5.0

  # Flutter package for Eva Icons
  # https://pub.dev/packages/eva_icons_flutter
  eva_icons_flutter: ^2.0.0

  # Easily add staggered animations to your ListView, GridView, Column and Row children as shown in Material Design guidelines
  # https://pub.dev/packages/flutter_staggered_animations
  flutter_staggered_animations: ^0.1.2

  # A Flutter staggered grid view which supports multiple columns with rows of varying sizes.
  # https://pub.dev/packages/flutter_staggered_grid_view
  flutter_staggered_grid_view: ^0.3.0

  # A library useful for creating fuzzy timestamps. (e.g. "5 minutes ago")
  # https://pub.dev/packages/timeago
  timeago: ^2.0.26

  # A dart package that helps implement the BLoC pattern.
  # https://pub.dev/packages/bloc
  bloc: ^4.0.0

  # A Flutter package that helps implement the BLoC pattern
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^4.0.0

  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization
  # https://pub.dev/packages/json_annotation
  json_annotation: ^3.0.1

  # Widget now uses builders for the placeholder and error widget and uses sqflite for cache management.
  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^2.2.0+1

  # A Flutter plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.
  # https://pub.dev/packages/image_picker
  image_picker: ^0.6.6+1

  # Being able to compare objects in Dart
  # https://pub.dev/packages/equatable
  equatable: ^1.1.1

  # A widget that can be dragged and scrolled in a single gesture and snapped to a list of extents.
  # https://pub.dev/packages/sliding_sheet
  sliding_sheet: ^0.3.5

  # A Flutter plugin for finding commonly used locations on the filesystem. Supports iOS and Android
  # https://pub.dev/packages/path_provider
  path_provider: ^1.6.8

  # A comprehensive, cross-platform path manipulation library for Dart.
  # https://pub.dev/packages/path
  path: ^1.7.0

  # This plugin provides a cross-platform (iOS, Android) API to request permissions and check their status.
  # https://pub.dev/packages/permission_handler
  permission_handler: ^5.0.0+hotfix.6

  # Customizable Icons for Flutter,Inspired by react-native-vector-icons
  # https://pub.dev/packages/flutter_icons
  flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Route generator
  # https://pub.dev/packages/auto_route_generator
  auto_route_generator: ^0.5.0

  # Build scripts
  build_runner: ^1.10.0

  # Launcher Icons generator for flutter
  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.7.5

  # Mockito (for testing)
  # https://pub.dev/packages/mockito
  mockito: ^4.1.1

  # Serialise Json
  # https://pub.dev/packages/json_serializable
  json_serializable: ^3.2.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.webp"

flutter:
  uses-material-design: true
  assets:
    - assets/lr/lr.webp
    - assets/br/br.webp
    - assets/kt/kt.webp
    - assets/welcome.svg
    - assets/logo/logo.webp
    - assets/logo/2x/logo.webp
    - assets/logo/3x/logo.webp
    - assets/logo/4x/logo.webp
